# Generated by Django 5.2.6 on 2025-09-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('animal_class', models.CharField(db_column='class', max_length=100)),
                ('order', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('habitat', models.CharField(max_length=255)),
                ('continent', models.CharField(max_length=50)),
                ('diet', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=100)),
                ('lifespan', models.CharField(max_length=50)),
                ('conservation_status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('fact', models.TextField()),
            ],
        ),
    ]
